language: php
sudo: false
dist: precise

branches:
  only:
    - master
    - staging

services:
  - mysql

php:
  - 5.5

git:
  depth: 5

env:
  global:
    - DB=mysql
  matrix:
    - MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    - MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    - MAGENTO_VERSION="magento-mirror-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    - MAGENTO_VERSION="magento-mirror-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=yes
    - MAGENTO_VERSION="magento-mirror-1.8.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    # Do not download sample data of 1.9 -> The file is too big
    - MAGENTO_VERSION="magento-mirror-1.9.0.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.1.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.2.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.2.2" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.2.3" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.2.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.2" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.6" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.7" DB=mysql INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.8" DB=mysql INSTALL_SAMPLE_DATA=no

matrix:
  fast_finish: true
  exclude:
    # Old Magento Versions are not officially supported to run with PHP 5.5
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=no
  include:
    # Lint PHP code with PHP 7.0
    - php: 7.0
      env: LINTSH=1
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.2.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.2" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.6" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.7" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.9.3.8" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.2.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.2" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.6" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.7" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.8" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.1
      env: MAGENTO_VERSION="magento-mirror-1.9.3.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.1
      env: MAGENTO_VERSION="magento-mirror-1.9.3.2" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.1
      env: MAGENTO_VERSION="magento-mirror-1.9.3.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.1
      env: MAGENTO_VERSION="magento-mirror-1.9.3.6" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.1
      env: MAGENTO_VERSION="magento-mirror-1.9.3.7" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.1
      env: MAGENTO_VERSION="magento-mirror-1.9.3.8" DB=mysql INSTALL_SAMPLE_DATA=no

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

before_script:
  - source build/travis/before_script.sh

script:
  - vendor/bin/phpunit --debug --stop-on-error --stop-on-failure
